"""empty message

Revision ID: 2e5307cb530e
Revises: 
Create Date: 2017-11-09 22:00:59.863277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e5307cb530e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=True),
    sa.Column('annual_risk', sa.Integer(), nullable=True),
    sa.Column('inspect_int', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ident')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('abbr', sa.String(length=64), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('mob_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hydro_release', sa.Float(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consequences_component_id'), 'consequences', ['component_id'], unique=False)
    op.create_table('subcomponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ident')
    )
    op.create_index(op.f('ix_subcomponents_component_id'), 'subcomponents', ['component_id'], unique=False)
    op.create_table('failure_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('mttf', sa.Float(), nullable=True),
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.Column('subcomponent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['subcomponent_id'], ['subcomponents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_modes_consequence_id'), 'failure_modes', ['consequence_id'], unique=False)
    op.create_index(op.f('ix_failure_modes_subcomponent_id'), 'failure_modes', ['subcomponent_id'], unique=False)
    op.create_table('vessel_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_time', sa.Float(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_trip_consequence_id'), 'vessel_trip', ['consequence_id'], unique=False)
    op.create_index(op.f('ix_vessel_trip_vessel_id'), 'vessel_trip', ['vessel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessel_trip_vessel_id'), table_name='vessel_trip')
    op.drop_index(op.f('ix_vessel_trip_consequence_id'), table_name='vessel_trip')
    op.drop_table('vessel_trip')
    op.drop_index(op.f('ix_failure_modes_subcomponent_id'), table_name='failure_modes')
    op.drop_index(op.f('ix_failure_modes_consequence_id'), table_name='failure_modes')
    op.drop_table('failure_modes')
    op.drop_index(op.f('ix_subcomponents_component_id'), table_name='subcomponents')
    op.drop_table('subcomponents')
    op.drop_index(op.f('ix_consequences_component_id'), table_name='consequences')
    op.drop_table('consequences')
    op.drop_table('vessels')
    op.drop_table('components')
    # ### end Alembic commands ###
