"""empty message

Revision ID: 599109fe883d
Revises: b48dea1302d6
Create Date: 2017-11-09 15:05:18.342714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599109fe883d'
down_revision = 'b48dea1302d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hydro_release', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('abbr', sa.String(length=64), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('mob_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consequence_vessels',
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consequence_vessels')
    op.drop_table('vessels')
    op.drop_table('consequences')
    # ### end Alembic commands ###
