"""empty message

Revision ID: 62df8e70f15c
Revises: 
Create Date: 2017-11-29 12:27:45.384292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62df8e70f15c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('remaining_life', sa.Float(), nullable=True),
    sa.Column('deferred_prod_cost', sa.Integer(), nullable=True),
    sa.Column('risk_cut_off', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcomponent_category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('time_dependant', sa.Boolean(), nullable=True),
    sa.Column('mean_time_to_failure', sa.Float(), nullable=True),
    sa.Column('detectable', sa.String(length=64), nullable=True),
    sa.Column('inspection_type', sa.String(length=64), nullable=True),
    sa.Column('consequence_description', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('equity_share', sa.Float(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_facility_id'), 'areas', ['facility_id'], unique=False)
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbr', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('day_rate', sa.Integer(), nullable=True),
    sa.Column('mob_time', sa.Float(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_facility_id'), 'vessels', ['facility_id'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('service_type', sa.String(length=64), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ident')
    )
    op.create_index(op.f('ix_components_area_id'), 'components', ['area_id'], unique=False)
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('mean_time_to_repair', sa.Float(), nullable=True),
    sa.Column('replacement_cost', sa.Integer(), nullable=True),
    sa.Column('deferred_prod_rate', sa.Float(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consequences_component_id'), 'consequences', ['component_id'], unique=False)
    op.create_index(op.f('ix_consequences_facility_id'), 'consequences', ['facility_id'], unique=False)
    op.create_table('fmecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fmecas_component_id'), 'fmecas', ['component_id'], unique=False)
    op.create_table('subcomponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcomponents_component_id'), 'subcomponents', ['component_id'], unique=False)
    op.create_table('rbis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=64), nullable=True),
    sa.Column('fmeca_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fmeca_id'], ['fmecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbis_fmeca_id'), 'rbis', ['fmeca_id'], unique=False)
    op.create_table('vessel_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_repair_time', sa.Float(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_trip_consequence_id'), 'vessel_trip', ['consequence_id'], unique=False)
    op.create_index(op.f('ix_vessel_trip_vessel_id'), 'vessel_trip', ['vessel_id'], unique=False)
    op.create_table('failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subcomponent_id', sa.Integer(), nullable=True),
    sa.Column('fmeca_id', sa.Integer(), nullable=True),
    sa.Column('failure_mode_id', sa.Integer(), nullable=True),
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.Column('rbi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['failure_mode_id'], ['failure_modes.id'], ),
    sa.ForeignKeyConstraint(['fmeca_id'], ['fmecas.id'], ),
    sa.ForeignKeyConstraint(['rbi_id'], ['rbis.id'], ),
    sa.ForeignKeyConstraint(['subcomponent_id'], ['subcomponents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failures_consequence_id'), 'failures', ['consequence_id'], unique=False)
    op.create_index(op.f('ix_failures_failure_mode_id'), 'failures', ['failure_mode_id'], unique=False)
    op.create_index(op.f('ix_failures_fmeca_id'), 'failures', ['fmeca_id'], unique=False)
    op.create_index(op.f('ix_failures_rbi_id'), 'failures', ['rbi_id'], unique=False)
    op.create_index(op.f('ix_failures_subcomponent_id'), 'failures', ['subcomponent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failures_subcomponent_id'), table_name='failures')
    op.drop_index(op.f('ix_failures_rbi_id'), table_name='failures')
    op.drop_index(op.f('ix_failures_fmeca_id'), table_name='failures')
    op.drop_index(op.f('ix_failures_failure_mode_id'), table_name='failures')
    op.drop_index(op.f('ix_failures_consequence_id'), table_name='failures')
    op.drop_table('failures')
    op.drop_index(op.f('ix_vessel_trip_vessel_id'), table_name='vessel_trip')
    op.drop_index(op.f('ix_vessel_trip_consequence_id'), table_name='vessel_trip')
    op.drop_table('vessel_trip')
    op.drop_index(op.f('ix_rbis_fmeca_id'), table_name='rbis')
    op.drop_table('rbis')
    op.drop_index(op.f('ix_subcomponents_component_id'), table_name='subcomponents')
    op.drop_table('subcomponents')
    op.drop_index(op.f('ix_fmecas_component_id'), table_name='fmecas')
    op.drop_table('fmecas')
    op.drop_index(op.f('ix_consequences_facility_id'), table_name='consequences')
    op.drop_index(op.f('ix_consequences_component_id'), table_name='consequences')
    op.drop_table('consequences')
    op.drop_index(op.f('ix_components_area_id'), table_name='components')
    op.drop_table('components')
    op.drop_index(op.f('ix_vessels_facility_id'), table_name='vessels')
    op.drop_table('vessels')
    op.drop_index(op.f('ix_areas_facility_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_table('failure_modes')
    op.drop_table('facilities')
    # ### end Alembic commands ###
