"""empty message

Revision ID: 72addd920a22
Revises: 9f9160187696
Create Date: 2017-11-08 16:13:26.899572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72addd920a22'
down_revision = '9f9160187696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcomponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ident')
    )
    op.create_index(op.f('ix_subcomponents_component_id'), 'subcomponents', ['component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcomponents_component_id'), table_name='subcomponents')
    op.drop_table('subcomponents')
    # ### end Alembic commands ###
