"""empty message

Revision ID: 73206fa1d1ed
Revises: 
Create Date: 2017-11-09 16:04:10.376308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73206fa1d1ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=True),
    sa.Column('annual_risk', sa.Integer(), nullable=True),
    sa.Column('inspect_int', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ident')
    )
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('abbr', sa.String(length=64), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('mob_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbr'),
    sa.UniqueConstraint('name')
    )
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('hydro_release', sa.Float(), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consequences_component_id'), 'consequences', ['component_id'], unique=False)
    op.create_table('subcomponents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ident', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ident')
    )
    op.create_index(op.f('ix_subcomponents_component_id'), 'subcomponents', ['component_id'], unique=False)
    op.create_table('consequence_vessels',
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consequence_vessels')
    op.drop_index(op.f('ix_subcomponents_component_id'), table_name='subcomponents')
    op.drop_table('subcomponents')
    op.drop_index(op.f('ix_consequences_component_id'), table_name='consequences')
    op.drop_table('consequences')
    op.drop_table('vessels')
    op.drop_table('components')
    # ### end Alembic commands ###
