"""empty message

Revision ID: aca79294292c
Revises: 599109fe883d
Create Date: 2017-11-09 15:09:12.375841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aca79294292c'
down_revision = '599109fe883d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consequences', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consequences', 'name')
    # ### end Alembic commands ###
