"""empty message

Revision ID: b305873c4810
Revises: 73206fa1d1ed
Create Date: 2017-11-09 18:55:34.130619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b305873c4810'
down_revision = '73206fa1d1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure_modes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('failure_prob', sa.Float(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('subcomponent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subcomponent_id'], ['subcomponents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failure_modes_subcomponent_id'), 'failure_modes', ['subcomponent_id'], unique=False)
    op.create_table('vessel_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_time', sa.Float(), nullable=True),
    sa.Column('vessel_id', sa.Integer(), nullable=True),
    sa.Column('consequence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessel_trip_consequence_id'), 'vessel_trip', ['consequence_id'], unique=False)
    op.create_index(op.f('ix_vessel_trip_vessel_id'), 'vessel_trip', ['vessel_id'], unique=False)
    op.drop_table('consequence_vessels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consequence_vessels',
    sa.Column('consequence_id', sa.INTEGER(), nullable=True),
    sa.Column('vessel_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['consequence_id'], ['consequences.id'], ),
    sa.ForeignKeyConstraint(['vessel_id'], ['vessels.id'], )
    )
    op.drop_index(op.f('ix_vessel_trip_vessel_id'), table_name='vessel_trip')
    op.drop_index(op.f('ix_vessel_trip_consequence_id'), table_name='vessel_trip')
    op.drop_table('vessel_trip')
    op.drop_index(op.f('ix_failure_modes_subcomponent_id'), table_name='failure_modes')
    op.drop_table('failure_modes')
    # ### end Alembic commands ###
