"""empty message

Revision ID: b48dea1302d6
Revises: 72addd920a22
Create Date: 2017-11-08 22:10:36.194483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b48dea1302d6'
down_revision = '72addd920a22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('annual_risk', sa.Numeric(), nullable=True))
    op.add_column('components', sa.Column('inspect_int', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'inspect_int')
    op.drop_column('components', 'annual_risk')
    # ### end Alembic commands ###
